config/routes.rb
OapDocuments::Application.routes.draw do
  get 'home/index'
  namespace :home do
    get "info2"
    get "info"
    get "iso"
    get 'download_file'
  end

  namespace :iso do
    get "tema1"
    get "tema2"
  end

  namespace :info do
    get "tema1"
  end

  namespace :info2 do
    get "tema1"
  end

  root :to => 'home#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def iso
  end

  def info
  end

  def info2
  end

  def download_file
    send_file Rails.root.to_s + '/app/assets/images/rails.png'
  end
end

app/controllers/info2_controller.rb
class Info2Controller < ApplicationController
  def tema1
  end
end

app/controllers/info_controller.rb
class InfoController < ApplicationController
  def tema1
  end
end

app/controllers/iso_controller.rb
class IsoController < ApplicationController
  def tema1
  end

  def tema2
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/home/index.html.haml
%h1 Descarga de documentos OAP
%ul
  %li
    = link_to "ISO", home_iso_path
  %li
    = link_to "Informática", home_info_path
  %li
    = link_to "Iformática especializada", home_info2_path

app/views/home/info.html.haml
%h1 Temas Informatica
%ul
  %li
    = link_to "Tema 1", info_tema1_path

app/views/home/info2.html.haml
%h1 Temas Informatica especializada
%ul
  %li
    = link_to "Tema 1", info2_tema1_path

app/views/home/iso.html.haml
%h1 Temas ISO
%ul
  %li
    = link_to "Tema 1", iso_tema1_path
  %li
    = link_to "Tema 2", iso_tema2_path

app/views/info/tema1.html.haml
%h1 Descarga de Informatica - Tema 1

app/views/info2/tema1.html.haml
%h1 Descarga de Informatica Especializada - Tema 1

app/views/iso/tema1.html.haml
%h1 Descarga de ISO - Tema 1
%ul
  %li
    = link_to 'descargar rails 1', home_download_file_path
  %li
    = link_to 'descargar rails 2', home_download_file_path
  %li
    = link_to 'descargar rails 3', home_download_file_path

app/views/iso/tema2.html.haml
%h1 Descarga de ISO - Tema 2

app/views/layouts/_back.html.haml
= link_to :back, class: "btn btn-primary btn-large pull-right" do
  .glyphicon.glyphicon-chevron-left
  Atrás

app/views/layouts/_nav_bar.html.haml
%nav.navbar.navbar-default.navbar-fixed-top{role: "navigation"}
  / Brand and toggle get grouped for better mobile display
  .navbar-header
    %button.navbar-toggle{"data-target" => ".navbar-ex1-collapse", "data-toggle" => "collapse", type: "button"}
      %span.sr-only Toggle navigation
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    = link_to root_path, class: 'navbar-brand' do
      %b Documentos OAP

  / Collect the nav links, forms, and other content for toggling
  .collapse.navbar-collapse.navbar-ex1-collapse
    %ul.nav.navbar-nav
      %li
        = link_to root_path do
          .glyphicon.glyphicon-align-justify
          Menú Principal

    = image_tag 'logo.png', class: 'pull-right', height: 80

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= content_for?(:title) ? yield(:title) : "Untitled"
    = stylesheet_link_tag "application"
    = javascript_include_tag :defaults
    = csrf_meta_tag
    = yield(:head)
  %body
    #wrap
      .container
        - flash.each do |name, msg|
          = content_tag :div, msg, :id => "flash_#{name}"
        = content_tag :h1, yield(:title) if show_title?
        = render :partial => "layouts/nav_bar"
        = yield
    #footer
      .container
        - unless params[:controller] == 'home' && params[:action] == 'index'
          = link_to :back, class: "btn btn-primary btn-large pull-right" do
            .glyphicon.glyphicon-chevron-left
            Atrás